[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Parquet = "626c502c-15b0-58ad-a749-f091afb673ae"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
